name: 
  /workspace/runs/talkative_building_crack/.conda/envs/talkative_building_crack_env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - conda-pack=0.8.1=pyhd8ed1ab_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsqlite=3.51.1=h0c1763c_0
  - libstdcxx=15.2.0=h934c35e_16
  - libuuid=2.41.2=h5347b49_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - numpy=2.3.5=py312h33ff503_0
  - openssl=3.6.0=h26f9b46_0
  - pandas=2.3.1=py312hf79963d_0
  - pip=25.3=pyh8b19718_0
  - python=3.12.0=hab00c5b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - readline=8.3=h853b02a_0
  - scikit-learn=1.7.1=py312h4f0b9e3_0
  - scipy=1.16.3=py312h7a1785b_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tzdata=2025c=h8577fbf_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==4.12.0
      - attrs==25.4.0
      - catboost==1.2.8
      - certifi==2025.11.12
      - chanfig==0.0.114
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cycler==0.12.1
      - danling==0.3.13
      - datasets==4.4.1
      - dill==0.4.0
      - einops==0.8.1
      - filelock==3.20.1
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - lazy-imports==1.1.0
      - lightgbm==4.6.0
      - lightning-utilities==0.15.2
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - multidict==6.7.0
      - multimolecule==0.0.8
      - multiprocess==0.70.18
      - narwhals==2.15.0
      - networkx==3.6.1
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - packaging==25.0
      - pillow==12.1.0
      - plotly==6.5.2
      - propcache==0.4.1
      - psutil==7.1.3
      - pyarrow==22.0.0
      - pyparsing==3.3.2
      - python-graphviz==0.21
      - pytorch-tabnet==4.1.0
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - smmap==5.0.2
      - sympy==1.14.0
      - tokenizers==0.21.4
      - torch==2.9.0
      - torcheval==0.0.7
      - torchmetrics==1.8.2
      - tqdm==4.67.1
      - transformers==4.47.1
      - triton==3.5.0
      - typing-extensions==4.15.0
      - urllib3==2.6.2
      - xgboost==1.7.6
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: 
  /workspace/runs/talkative_building_crack/.conda/envs/talkative_building_crack_env
